### ISSUE TITLE
with PrefixStackTrace does not throw properly

### ISSUE THREAD

**Issue by pjanowski** [Azure/confidential-ml-utils#23]
This code
```
        with PrefixStackTrace(keep_message=False):
            10 / 0
```

results in this log (which is fine)

```
SystemLog: Traceback (most recent call last):
SystemLog:   File "/mnt/c/code/confidential-ml-utils/src/confidential_ml_utils/exceptionExtractor.py", line 130, in extract
SystemLog:     10 / 0
SystemLog: ZeroDivisionError: **Exception message scrubbed**
```

and then throws the following. The thrown exception message is not scrubbed:
```

Traceback (most recent call last):
  File "/mnt/c/code/confidential-ml-utils/src/confidential_ml_utils/exceptionExtractor.py", line 141, in <module>
    ee.extract("../tests/log.rr")
  File "/mnt/c/code/confidential-ml-utils/src/confidential_ml_utils/exceptionExtractor.py", line 130, in extract
    10 / 0
  File "/home/pawelrc/miniconda3/envs/confaml/lib/python3.7/site-packages/confidential_ml_utils/exceptions.py", line 173, in __exit__
    self.file, self.prefix, self.scrub_message, self.keep_message
  File "/mnt/c/code/confidential-ml-utils/src/confidential_ml_utils/exceptionExtractor.py", line 130, in extract
    10 / 0
ZeroDivisionError: division by zero
```

**Comment by dkmiller** [comment]
@pjanowski I'm assigning this to you for now, I'm guessing we're just not passing the `keep_message` parameter properly. Let me know if you need any help with tests or debugging.
