### ISSUE TITLE
This library can't properly scrub JSON from REST API exceptions

### ISSUE THREAD

**Issue by dkmiller** [Azure/confidential-ml-utils#71]
Write code similar to:

```python
from azureml.core import Run
from pytorch_lightning.loggers import MLFlowLogger

run = Run.get_context()
mlflow_uri = run.experiment.workspace.get_mlflow_tracking_uri()
exp_name = run.experiment.name

logger = MLFlowLogger(experiment_name=exp_name, tracking_uri=mlflow_uri)
logger._run_id = run.id

self.logger_type = "aml"
self.logger = run
```

Then, getting the following exception when trying `logger.log_hyperparams`:

> confidential_ml_utils.exceptions.PublicRuntimeError: SystemLog: Obtained ValueError when trying to scrub json from RestException

**Comment by dkmiller** [comment]
Additional context. The failure is coming from an attempt to log hyperparameters with the same `{name: value}`.

Should still eventually attempt to fix: https://www.mlflow.org/docs/latest/_modules/mlflow/exceptions.html .

**Comment by fuhuifang** [comment]
Reproducing locally:
```python
from azureml.core import Run
from pytorch_lightning.loggers import MLFlowLogger

run = Run.get_context()
logger = MLFlowLogger(experiment_name="test")#, tracking_uri=mlflow_uri)
```

Case 1:
```python
logger.log_hyperparams({"log_test":"aaa"})
logger.log_hyperparams({"log_test":"bbb"})
```

Error:
```
Traceback (most recent call last):
  File "c:/Users/fufang/repo/confidential-ml-utils/src/test.py", line 12, in <module>
    logger.log_hyperparams({"log_test":"bbb"})
  File "C:\Users\fufang\Miniconda3\envs\py38\lib\site-packages\pytorch_lightning\utilities\distributed.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
  File "C:\Users\fufang\Miniconda3\envs\py38\lib\site-packages\pytorch_lightning\loggers\mlflow.py", line 159, in log_hyperparams
    self.experiment.log_param(self.run_id, k, v)
  File "C:\Users\fufang\Miniconda3\envs\py38\lib\site-packages\mlflow\tracking\client.py", line 674, in log_param
    self._tracking_client.log_param(run_id, key, value)
  File "C:\Users\fufang\Miniconda3\envs\py38\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 190, in log_param
    self.store.log_param(run_id, param)
  File "C:\Users\fufang\Miniconda3\envs\py38\lib\site-packages\mlflow\store\tracking\file_store.py", line 763, in log_param
    self._log_run_param(run_info, param)
  File "C:\Users\fufang\Miniconda3\envs\py38\lib\site-packages\mlflow\store\tracking\file_store.py", line 769, in _log_run_param
    self._validate_new_param_value(
  File "C:\Users\fufang\Miniconda3\envs\py38\lib\site-packages\mlflow\store\tracking\file_store.py", line 789, in _validate_new_param_value
    raise MlflowException(
mlflow.exceptions.MlflowException: Changing param values is not allowed. Param with key='log_test' was already logged with value='aaa' for run ID='17e7c2d6bf894ea98b733eb1428dcf65'. Attempted logging new value 'bbb'.
```
Case 2:
```python
logger.log_hyperparams({"log_test":"aaa"})
logger.log_hyperparams({"log_test":"aaa"})
```
No error.
